MOUSEKEY_ENABLE = yes    # Mouse keys
# RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight. 
RGB_MATRIX_ENABLE = yes
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
VIA_ENABLE      = no  
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes